export const SET_BREADCRUMB_STATE = 'SET_BREADCRUMB_STATE';
export const FETCH_KEYWORDS = 'FETCH_KEYWORDS';
export const FETCH_KEYWORD_RESULTS = 'FETCH_KEYWORD_RESULTS';
export const CLEAR_KEYWORD_RESULTS = 'CLEAR_KEYWORD_RESULTS';
export const FETCH_KEYWORD_ARTICLES = 'FETCH_KEYWORD_ARTICLES';
export const FETCH_TWEET_STATS = 'FETCH_TWEET_STATS';
export const FETCH_HASHTAGS = 'FETCH_HASHTAGS';
export const FETCH_CALCED_GRAPHS = 'FETCH_CALCED_GRAPHS';