export const SET_BREADCRUMB_STATE = 'SET_BREADCRUMB_STATE';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_CALCED_GRAPHS = 'FETCH_CALCED_GRAPHS';
export const FETCH_TWEET_STATS = 'FETCH_TWEET_STATS';